version: "3.9"
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coord
    ports:
      - 3306:3306
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS='mysql'
    ports:
      - "9000:80"

  ui:
    container_name: ui
    build: ./ui
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./server
    ports:
      - "8000:8000"
    environment:
      PORT: "8000"
      MYSQL_URL: "mysql"
      MYSQL_PORT: "3306"
    depends_on:
      - mysql
